apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami.yaml
  - bjw-s.yaml
  - cert-manager-webhook-powerdns-charts.yaml
  - cilium-charts.yaml
  - external-dns-charts.yaml
  - gitea-charts.yaml
  - hajimari.yaml
  - ingress-nginx.yaml
  - jetstack.yaml
  - k8s-gateway.yaml
  - kubernetes-sigs-descheduler-charts.yaml
  - kubernetes-sigs-metrics-server-charts.yaml
  - metallb-charts.yaml
